apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pangolin-helm
  namespace: argocd
spec:
  destination:
    namespace: newt
    server: https://kubernetes.default.svc
  project: platform
  source:
    chart: newt
    repoURL: https://charts.fossorial.io
    targetRevision: 1.5.0
    helm:
      valuesObject:
        newtInstances:
          - name: main-tunnel
            enabled: true
            acceptClients: true
            auth:
              existingSecretName: newt-main-tunnel-auth
  syncPolicy:
    automated:
      # Prune resources during auto-syncing (default is false)
      prune: true 
      # Sync the app in part when resources are changed only in the target Kubernetes cluster
      # but not in the git source (default is false).
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true